#!/usr/bin/env Rscript
# figure5.R — Pre-diagnostic comorbidity endophenotypes in MS
#
# Pipeline dependencies (must be run first):
#   14_comorbidity/02a_ms_prems_phewas.R
#   15_endophenotype/02_ms_prems_comorbidity_endophenotype.R
#   15_endophenotype/04_ms_cluster_proteomics.R   ← panels G–J
#
# Panels produced (individual PDFs, no composite):
#   a  PheWAS lollipop — 23 pre-MS FDR<0.05 associations
#   b  Cluster UMAP — C0/C1/C2 (None as grey background)
#   c  Block enrichment heatmap — 11 blocks × 3 clusters
#   d  Age at MS diagnosis — violin + box by cluster
#   e  HLA-DRB1*15:01 carrier rate — lollipop by cluster
#   f  MS polygenic risk score — violin + box by cluster
#   g–i  (generated by 04_ms_cluster_proteomics.R after DEP results)
#
# Output: results/figures/5/panel_*.pdf

suppressPackageStartupMessages({
    library(data.table)
    library(ggplot2)
    library(ggrepel)
    library(patchwork)
    library(glue)
})

args       <- commandArgs(trailingOnly = FALSE)
file_arg   <- grep("^--file=", args, value = TRUE)
SCRIPT_DIR <- if (length(file_arg)) dirname(normalizePath(sub("^--file=", "", file_arg))) else getwd()
PROJ_DIR   <- normalizePath(file.path(SCRIPT_DIR, "..", ".."))
source(file.path(PROJ_DIR, "analysis", "helpers", "ukb_theme.R"))
source(file.path(PROJ_DIR, "analysis", "helpers", "disease_config.R"))

cfg          <- load_disease_config()
COHORT       <- cfg$cohort_short
DISEASE_CAPS <- cfg$disease_short_caps
HLA_LBL      <- paste0("HLA-", cfg$hla_allele)
PRS_LABEL    <- cfg$prs_label
PRS_COL      <- cfg$prs_combined_col
HLA_CARRIER  <- cfg$hla_carrier_col
PRE_LBL      <- glue("pre-{DISEASE_CAPS}")

FIG_DIR   <- file.path(PROJ_DIR, "results", "figures", "5")
ENDO_DIR  <- file.path(PROJ_DIR, "results", "endophenotype")
COMOR_DIR <- file.path(PROJ_DIR, "results", "comorbidity")
dir.create(FIG_DIR, showWarnings = FALSE, recursive = TRUE)

save_panel <- function(p, name, w, h) {
    out <- file.path(FIG_DIR, sprintf("panel_%s.pdf", name))
    ggsave(out, p, width = w, height = h, device = cairo_pdf)
    cat(sprintf("  panel_%s.pdf  (%g × %g in)\n", name, w, h))
    invisible(p)
}

set.seed(42)

# Extend ukb_theme CLUST_COLS with "None" entry for this figure
CLUST_COLS <- c(CLUST_COLS, "None" = "grey60")

CHAP_COLS <- c(
    B = "#9DB66A", E = "#20B2AA", G = "#2B4C7E", H = "#5B9BD5",
    I = "#E6A817", J = "#4CAF50", K = "#A0522D", L = "#CC0066",
    M = "#9370DB", N = "#20B2AA", R = "#607D8B", Z = "#9E9E9E"
)

ICD_LABELS <- c(
    H46 = "Optic neuritis",         R26 = "Gait abnormality",
    G51 = "Facial nerve palsy",     R29 = "Neurological symptoms NEC",
    R20 = "Sensory disturbance",    N17 = "Acute kidney injury",
    R79 = "Abnormal blood result",  M45 = "Ankylosing spondylitis",
    K76 = "Liver disorder",         B27 = "Infectious mononucleosis",
    M50 = "Cervical disc disorder", Z86 = "Personal disease history",
    H25 = "Cataract",
    I10 = "Hypertension",           E78 = "Lipid disorder",
    M19 = "Arthrosis",              J06 = "Upper resp. infection",
    L30 = "Dermatitis NOS",         Z37 = "Outcome of delivery",
    M25 = "Joint disorder NEC",     L98 = "Skin disorder NEC",
    N63 = "Breast lump",            K21 = "Gastro-oesophageal reflux"
)

BLOCK_LABELS <- c(
    H4 = "H4  Optic / eye",         R2 = "R2  Neurological sx",
    B2 = "B2  EBV / viral",         G5 = "G5  Cranial nerve",
    Z8 = "Z8  Personal history",    M5 = "M5  Cervical disc",
    H2 = "H2  Cataract",            M4 = "M4  Spondyloarthritis",
    R7 = "R7  Blood abnormality",   N1 = "N1  Renal",
    K7 = "K7  Liver"
)

# ── Load data ─────────────────────────────────────────────────────────────────
cat("Loading data...\n")
phewas    <- fread(file.path(COMOR_DIR, glue("{COHORT}_prems_phewas.csv")))
blk_feat  <- fread(file.path(ENDO_DIR,  glue("{COHORT}_prems_block_features.csv")))
clust_sum <- fread(file.path(ENDO_DIR,  glue("{COHORT}_prems_cluster_summary.csv")))
overrep   <- fread(file.path(ENDO_DIR,  glue("{COHORT}_prems_block_overrep.csv")))
config    <- fread(file.path(ENDO_DIR,  glue("{COHORT}_prems_umap_config.csv")))
# Normalise PRS / HLA carrier columns to fixed sentinels so downstream code is
# disease-agnostic.
if (PRS_COL != "prs_score" && PRS_COL %in% names(blk_feat))
    setnames(blk_feat, PRS_COL, "prs_score")
if (HLA_CARRIER != "hla_carrier" && HLA_CARRIER %in% names(blk_feat))
    setnames(blk_feat, HLA_CARRIER, "hla_carrier")

enr_blocks     <- strsplit(config$blocks, ",")[[1]]
cluster_levels <- c(paste0("C", 0:(config$k - 1)), "None")

blk_feat[, cluster_f := factor(
    ifelse(is.na(cluster), "None", paste0("C", cluster)),
    levels = cluster_levels
)]

cat(sprintf("  PheWAS: %d tested, %d FDR<0.05  |  clusters: k=%d, sil=%.3f\n",
            nrow(phewas), sum(phewas$fdr < 0.05),
            config$k, config$silhouette))

# Sex composition per cluster (UKB: sex=1 is female)
sex_comp <- blk_feat[!is.na(sex), .(pct_female = 100 * mean(sex == 1), n = .N), by = cluster_f]
sex_chi  <- chisq.test(table(blk_feat[!is.na(sex)]$cluster_f,
                              blk_feat[!is.na(sex)]$sex))
sex_chi_p <- sex_chi$p.value
cat(sprintf("  Sex composition (%%F): %s  |  chi2 p=%.3f\n",
            paste(sprintf("%s=%.0f%%", sex_comp$cluster_f, sex_comp$pct_female), collapse="  "),
            sex_chi_p))

# ── Panel A: Pre-MS PheWAS lollipop ──────────────────────────────────────────
cat("\nPanel A...\n")

sig <- phewas[fdr < 0.05][order(log2(OR))]
sig[, log2or    := log2(OR)]
sig[, chap_col  := CHAP_COLS[chapter]]
sig[, chap_col  := fcase(is.na(chap_col), "grey55", default = chap_col)]
sig[, direction := factor(ifelse(OR > 1, glue("Enriched {PRE_LBL}"), glue("Depleted {PRE_LBL}")),
                           levels = c(glue("Enriched {PRE_LBL}"), glue("Depleted {PRE_LBL}")))]
sig[, lbl       := paste0(icd10, "  ", ICD_LABELS[icd10])]
sig[, lbl       := factor(lbl, levels = lbl)]   # ordered by OR

pA <- ggplot(sig, aes(x = log2or, y = lbl, colour = chap_col)) +
    geom_vline(xintercept = 0, linewidth = 0.3, colour = "grey40") +
    geom_segment(aes(x = 0, xend = log2or, yend = lbl),
                 linewidth = 0.65, alpha = 0.75) +
    geom_point(aes(size = -log10(pval)), alpha = 0.95) +
    scale_colour_identity() +
    scale_size_continuous(
        range  = c(1.5, 5.5),
        breaks = c(2, 5, 10, 20),
        name   = expression(-log[10](italic(p)))
    ) +
    scale_x_continuous(
        name   = bquote(log[2](OR) ~ "vs age-matched HC before"~.(DISEASE_CAPS)~"diagnosis"),
        breaks = seq(-4, 6, 2)
    ) +
    facet_grid(direction ~ ., scales = "free_y", space = "free_y") +
    labs(y = NULL,
         title    = glue("a  {PRE_LBL} comorbidity associations"),
         subtitle = sprintf("%d conditions tested | %d FDR<0.05 | model: age + sex",
                            nrow(phewas), nrow(sig))) +
    theme_ukb(base_size = 9) +
    theme(
        strip.text         = element_text(size = 7.5, face = "bold", colour = "grey30"),
        panel.grid.major.y = element_line(colour = "grey94", linewidth = 0.25),
        axis.text.y        = element_text(size = 7.5),
        legend.position    = "right",
        legend.key.height  = unit(0.6, "lines")
    )

save_panel(pA, "a", w = 7.0, h = 5.5)

# ── Panel B: Cluster UMAP ─────────────────────────────────────────────────────
cat("Panel B...\n")

# Only patients WITH pre-MS features have UMAP coordinates (U1/U2 = NA for None)
umap_pts <- blk_feat[!is.na(U1)]
umap_pts[, cluster_f := factor(cluster_f, levels = c("C0","C1","C2"))]

pB <- ggplot(umap_pts, aes(U1, U2, colour = cluster_f)) +
    geom_point(size = 1.2, alpha = 0.85, stroke = 0) +
    scale_colour_manual(
        values = c("C0" = "#E6A817", "C1" = "#CC0066", "C2" = "#2B4C7E"),
        name   = NULL,
        labels = c("C0" = "C0 (spine / connective)",
                   "C1" = "C1 (cranial nerve / demyelinating)",
                   "C2" = "C2 (neurological sx + EBV)")
    ) +
    guides(colour = guide_legend(
        override.aes = list(size = 2.8, alpha = 1),
        keyheight    = unit(0.55, "lines")
    )) +
    labs(x = "UMAP 1", y = "UMAP 2",
         title    = glue("b  {PRE_LBL} endophenotype clusters"),
         subtitle = sprintf("Jaccard UMAP  |  k=%d  |  sil=%.2f  |  n=%d patients with %s features  (n=%d without not shown)",
                            config$k, config$silhouette, config$n_clustered,
                            PRE_LBL, nrow(blk_feat) - config$n_clustered)) +
    theme_ukb(base_size = 9) +
    theme(axis.text = element_blank(), axis.ticks = element_blank(), aspect.ratio = 1,
          legend.position = "right",
          legend.text     = element_text(size = 7.5),
          legend.key.size = unit(0.55, "lines"))

save_panel(pB, "b", w = 3.8, h = 3.8)

# ── Panel C: Block enrichment heatmap ─────────────────────────────────────────
cat("Panel C...\n")

heat <- overrep[, .(block, cluster_f = paste0("C", cluster),
                     OR_cap = pmin(OR, 10), pct_in, sig = fdr < 0.05)]
heat[, blk_lab  := factor(BLOCK_LABELS[block],
                            levels = rev(BLOCK_LABELS[enr_blocks]))]
heat[, clust_f  := factor(cluster_f, levels = paste0("C", 0:(config$k - 1)))]

# n per cluster for x-axis labels
n_by_clust <- clust_sum[cluster_f != "None", .(cluster_f, n)]

x_labels <- setNames(
    sprintf("%s\nn=%d", n_by_clust$cluster_f, n_by_clust$n),
    n_by_clust$cluster_f
)

# ── Panel C: ICD block prevalence heatmap ────────────────────────────────────
cat("Panel C (% prevalence)...\n")

# Complete the block × cluster grid — overrep only contains rows where the
# block exists in that cluster; fill missing combos with pct_in = 0
full_grid <- CJ(block  = enr_blocks,
                clust_f = paste0("C", 0:(config$k - 1)))
heat_pct <- merge(full_grid,
                   heat[, .(block, clust_f = as.character(clust_f), pct_in)],
                   by = c("block", "clust_f"), all.x = TRUE)
heat_pct[is.na(pct_in), pct_in := 0]
heat_pct[, blk_lab := factor(BLOCK_LABELS[block],
                               levels = rev(BLOCK_LABELS[enr_blocks]))]
heat_pct[, clust_f := factor(clust_f, levels = paste0("C", 0:(config$k - 1)))]

pC <- ggplot(heat_pct, aes(x = clust_f, y = blk_lab, fill = pct_in)) +
    geom_tile(colour = "white", linewidth = 0.5) +
    scale_fill_gradient(
        low = "white", high = "#CC0066",
        limits = c(0, 100), na.value = "grey95",
        name = "% of cluster\nwith block"
    ) +
    scale_x_discrete(labels = x_labels) +
    labs(x = NULL, y = NULL,
         title    = "c  ICD block prevalence by cluster",
         subtitle = "% of cluster patients with each ICD block") +
    theme_ukb(base_size = 9) +
    theme(axis.text.x = element_text(face = "bold", size = 8.5, lineheight = 1.1),
          axis.text.y = element_text(size = 7.5),
          legend.key.width = unit(0.45, "cm"))

save_panel(pC, "c", w = 4.2, h = 4.2)

# ── Panel D: Age at diagnosis — violin + box ──────────────────────────────────
cat("Panel D...\n")

pD <- ggplot(blk_feat[!is.na(age_at_diagnosis)],
             aes(x = cluster_f, y = age_at_diagnosis, fill = cluster_f)) +
    geom_violin(trim = TRUE, linewidth = 0.25, alpha = 0.80) +
    geom_boxplot(width = 0.12, outlier.shape = NA, linewidth = 0.3,
                 fill = "white", colour = "grey30") +
    scale_fill_manual(values = CLUST_COLS, guide = "none") +
    labs(x = NULL, y = glue("Age at {DISEASE_CAPS} diagnosis (years)"),
         title    = "d  Age at diagnosis",
         subtitle = sprintf("n=%d MS cases  |  sex (%% female): %s  (χ² p=%.2f)",
                            nrow(blk_feat[!is.na(age_at_diagnosis)]),
                            paste(sprintf("%s %.0f%%", sex_comp$cluster_f, sex_comp$pct_female),
                                  collapse = "  "),
                            sex_chi_p)) +
    theme_ukb(base_size = 9) +
    theme(axis.text.x = element_text(face = "bold", size = 8))

save_panel(pD, "d", w = 3.2, h = 3.5)

# ── Panel E: HLA-DRB1*15:01 carrier rate — lollipop ─────────────────────────
cat("Panel E...\n")

if ("hla_carrier" %in% names(blk_feat)) {
    hla_dt <- blk_feat[!is.na(hla_carrier),
                        .(pct = 100 * mean(hla_carrier == 1), n = .N),
                        by = cluster_f]
    hla_dt[, cluster_f := factor(cluster_f, levels = cluster_levels)]
    hla_overall <- 100 * mean(blk_feat$hla_carrier == 1, na.rm = TRUE)

    # Fisher test: each cluster vs None
    none_hla <- blk_feat[cluster_f == "None" & !is.na(hla_carrier), hla_carrier]
    hla_pvals <- sapply(paste0("C", 0:(config$k - 1)), function(cl) {
        cl_hla <- blk_feat[cluster_f == cl & !is.na(hla_carrier), hla_carrier]
        fisher.test(matrix(c(sum(cl_hla == 1), sum(cl_hla == 0),
                              sum(none_hla == 1), sum(none_hla == 0)), nrow = 2))$p.value
    })
    hla_dt[, p_vs_none := hla_pvals[as.character(cluster_f)]]
    hla_dt[, p_label := fcase(
        is.na(p_vs_none) | cluster_f == "None", "",
        p_vs_none < 0.001, "p<0.001",
        default = sprintf("p=%.2f", p_vs_none)
    )]
    hla_dt[, y_label := pct + max(pct) * 0.06]

    pE <- ggplot(hla_dt, aes(x = cluster_f, y = pct, colour = cluster_f)) +
        geom_hline(yintercept = hla_overall,
                   linetype = "dashed", linewidth = 0.3, colour = "grey45") +
        geom_segment(aes(xend = cluster_f, y = 0, yend = pct),
                     linewidth = 1.0) +
        geom_point(size = 4.0) +
        scale_colour_manual(values = CLUST_COLS, guide = "none") +
        scale_y_continuous(limits = c(0, NA),
                           expand = expansion(mult = c(0, 0.18))) +
        labs(x = NULL, y = glue("{HLA_LBL} carrier (%)"),
             title    = "e  HLA carrier rate",
             subtitle = sprintf("Dashed = cohort mean  (overall: %.0f%%)  |  Fisher test vs None",
                                hla_overall)) +
        theme_ukb(base_size = 9) +
        theme(axis.text.x = element_text(face = "bold", size = 8))

    save_panel(pE, "e", w = 3.2, h = 3.5)
}

# ── Panel F: MS polygenic risk score — violin + box ─────────────────────────
cat("Panel F...\n")

if ("prs_score" %in% names(blk_feat)) {
    kw_prs   <- kruskal.test(prs_score ~ cluster_f, data = blk_feat[!is.na(prs_score)])
    kw_label <- if (kw_prs$p.value < 0.001) "KW p<.001" else sprintf("KW p=%.3f", kw_prs$p.value)

    pF <- ggplot(blk_feat[!is.na(prs_score)],
                 aes(x = cluster_f, y = prs_score, fill = cluster_f)) +
        geom_violin(trim = TRUE, linewidth = 0.25, alpha = 0.80) +
        geom_boxplot(width = 0.12, outlier.shape = NA, linewidth = 0.3,
                     fill = "white", colour = "grey30") +
        scale_fill_manual(values = CLUST_COLS, guide = "none") +
        labs(x = NULL, y = glue("{DISEASE_CAPS} polygenic risk score"),
             title    = "f  Polygenic risk score",
             subtitle = sprintf("Higher = greater common variant %s risk  |  %s",
                                DISEASE_CAPS, kw_label)) +
        theme_ukb(base_size = 9) +
        theme(axis.text.x = element_text(face = "bold", size = 8))

    save_panel(pF, "f", w = 3.2, h = 3.5)
}

cat("\nfigure5.R complete (panels a–f).\n")
cat("Run 04_ms_cluster_proteomics.R to generate panels g–i.\n")
